import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";
import { cn } from "@/utils/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "dark relative flex h-screen overflow-hidden bg-background font-sans antialiased",
          fontSans.variable,
          process.env.NODE_ENV === "development" && "debug-screens",
        )}
      >
        <Sidebar />
        <div className="h-screen w-full overflow-y-scroll px-12 py-9">
          {children}
        </div>
      </body>
    </html>
  );
}
