import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/Sidebar/Sidebar";
import "./globals.css";
import { cn } from "./utils/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("debug-screens flex bg-zinc-900", inter.className)}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
